dependencies:
- cairo=1.12.18=6
- cloog=0.18.0=0
- cycler=0.10.0=py35_0
- decorator=4.0.10=py35_0
- entrypoints=0.2.2=py35_0
- fontconfig=2.11.1=6
- freetype=2.5.5=1
- gcc=4.8.5=6
- glib=2.43.0=1
- gmp=5.1.2=2
- harfbuzz=0.9.39=1
- ipykernel=4.3.1=py35_0
- ipython=5.0.0=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=4.1.1=py35_0
- isl=0.12.2=0
- jinja2=2.8=py35_1
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=4.3.0=py35_0
- jupyter_console=5.0.0=py35_0
- jupyter_core=4.1.0=py35_0
- libffi=3.2.1=0
- libpng=1.6.22=0
- libsodium=1.0.10=0
- libxml2=2.9.2=0
- markupsafe=0.23=py35_2
- matplotlib=1.5.1=np111py35_0
- mistune=0.7.2=py35_0
- mkl=11.3.3=0
- mpc=1.0.1=0
- mpfr=3.1.2=0
- nbconvert=4.2.0=py35_0
- nbformat=4.0.1=py35_0
- notebook=4.2.1=py35_0
- numpy=1.11.1=py35_0
- openssl=1.0.2h=1
- pango=1.39.0=1
- path.py=8.2.1=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.7.3=py35_0
- pip=8.1.2=py35_0
- pixman=0.32.6=0
- prompt_toolkit=1.0.3=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.1.3=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=4.11.4=py35_4
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- pytz=2016.6.1=py35_0
- pyzmq=15.3.0=py35_0
- qt=4.8.7=4
- qtconsole=4.2.1=py35_0
- readline=6.2=2
- setuptools=23.0.0=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- terminado=0.6=py35_0
- tk=8.5.18=0
- tornado=4.4.1=py35_0
- traitlets=4.2.2=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zeromq=4.1.4=0
- zlib=1.2.8=3
- bryanwweber::cantera=2.2.1=np111py35_4
- bryanwweber::sundials=2.6.2=3
- pip:
  - cantera==2.2.1
  - ipython-genutils==0.1.0
  - jupyter-client==4.3.0
  - jupyter-console==5.0.0
  - jupyter-core==4.1.0
  - prompt-toolkit==1.0.3
